/**/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	alidnsaccountv1 "github.com/xzzpig/alidns-ingress-updater/pkg/apis/alidnsaccount/v1"
	versioned "github.com/xzzpig/alidns-ingress-updater/pkg/client/clientset/versioned"
	internalinterfaces "github.com/xzzpig/alidns-ingress-updater/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/xzzpig/alidns-ingress-updater/pkg/client/listers/alidnsaccount/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AliDnsAccountInformer provides access to a shared informer and lister for
// AliDnsAccounts.
type AliDnsAccountInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AliDnsAccountLister
}

type aliDnsAccountInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAliDnsAccountInformer constructs a new informer for AliDnsAccount type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAliDnsAccountInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAliDnsAccountInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAliDnsAccountInformer constructs a new informer for AliDnsAccount type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAliDnsAccountInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XzzpigV1().AliDnsAccounts().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XzzpigV1().AliDnsAccounts().Watch(context.TODO(), options)
			},
		},
		&alidnsaccountv1.AliDnsAccount{},
		resyncPeriod,
		indexers,
	)
}

func (f *aliDnsAccountInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAliDnsAccountInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *aliDnsAccountInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&alidnsaccountv1.AliDnsAccount{}, f.defaultInformer)
}

func (f *aliDnsAccountInformer) Lister() v1.AliDnsAccountLister {
	return v1.NewAliDnsAccountLister(f.Informer().GetIndexer())
}
