/**/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/xzzpig/alidns-ingress-updater/pkg/client/clientset/versioned/typed/alidnsaccount/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeXzzpigV1 struct {
	*testing.Fake
}

func (c *FakeXzzpigV1) AliDnsAccounts() v1.AliDnsAccountInterface {
	return &FakeAliDnsAccounts{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeXzzpigV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
