/**/
// Code generated by lister-gen. DO NOT EDIT.

package v1

// AliDnsAccountListerExpansion allows custom methods to be added to
// AliDnsAccountLister.
type AliDnsAccountListerExpansion interface{}
